### ISSUE TITLE
Basic questions 

### ISSUE THREAD

**Issue by travisghansen** [GuySie/ha-meural#25]
Thanks for the integration! I’ve not purchased one of these devices but am interested. Got a couple questions if you can help:

- can this integration and the device be used without ever getting/using the ‘cloud’ aspect? Can I buy it and use this immediately without siging up for any account anywhere?
- can you send the device arbitrary urls to load images? For example URLs from photos in flickr or a static google maps image, etc?
- any considerations between the 2 models in terms of which is ‘better’ both from the integration perspective and just generally?

**Comment by GuySie** [comment]
Hey @travisghansen sure!

>can this integration and the device be used without ever getting/using the ‘cloud’ aspect? Can I buy it and use this immediately without siging up for any account anywhere?

Sadly, no. The device arrives dormant and until you have registered a Meural account on their server and connected the device to your account, you can't actually use it at all. 

After registering, there is support for using it mostly locally - there's an SD card on the side for images (though you're limited to 4 folders/playlists) and a local web remote that you can use to control it - but there are several settings that are not exposed in either the local remote or on the device itself. This includes things like how long each images should be displayed and if images should be shuffled. Theoretically you could set all these settings properly once, and then never touch the cloud again.

This is also why the integration requires polling the Meural cloud API, because these settings aren't exposed locally.

>can you send the device arbitrary urls to load images? For example URLs from photos in flickr or a static google maps image, etc?

Yes, that is currently implemented in the `media_player.play_media` and `meural.preview_image` services (functionality is the same in both, but play_media can also take Meural item IDs to play). Send a JPG or PNG url and it will display fine - though @thomasvs who wrote the code mentioned there is a bug on Meural's side that sometimes make the device unresponsive. I have not encountered the bug yet.

The only caveat is that this uses a system Meural calls 'previewing' to temporarily override the artwork that was displaying. The preview duration is one of those settings that is not available locally, so you need to set it in the cloud. I believe the default setting for preview is something like 60 seconds. I haven't tested it but theoretically you could make the preview duration just as long as the normal image duration, and you wouldn't notice the difference between the 2 types.

>any considerations between the 2 models in terms of which is ‘better’ both from the integration perspective and just generally?

I only have used a Canvas II so can't comment on the previous model. It works fine for me!

1 thing I want to mention in general - the Canvas devices currently only have ambient light sensors for light intensity, but not for color temperature. Some newer competitors (like the Google hub, but also Lenovo's recently announced art frame) have color temperature correction on their display, which does help in making the frame look more natural in non-daylight lighting. In the evening, when your room is dim and you're using warm lamps, it becomes noticeable that the Canvas' white matte and the wall behind it are tinted towards yellow - but the Canvas images won't have that same tint and will still display pure whites.

**Comment by travisghansen** [comment]
Thanks for the great responses! I may have some follow ups and so maybe leave this ticket open for a little bit. I'll research the other options you mentioned and see if I'm interested in purchasing something (completely new to the arena so haven't done much research yet).

**Comment by jhein05** [comment]
Hi and thanks for the great explanation. 

If you don't mind a question: Can the color temperature of the screen set manually? If yes, one could probably implement something in HA, that changes the color temperature based on time of day, some external sensor, or sync the color temp with other smart bulbs in use.

**Comment by GuySie** [comment]
> If you don't mind a question: Can the color temperature of the screen set manually?

Sadly not, or at least there are no functions currently publicly exposed that would let us do so.
