### ISSUE TITLE
403 Accessing Meural API

### ISSUE THREAD

**Issue by gergles** [GuySie/ha-meural#27]
I just installed v1.0.2 into my hass virtualenv install and have this error accessing the API:

2020-08-08 11:54:16 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up meural platform for media_player
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 187, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 293, in async_add_entities
    await asyncio.gather(*tasks)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 450, in _async_add_entity
    await entity.async_added_to_hass()
  File "/home/homeassistant/.homeassistant/custom_components/meural/media_player.py", line 158, in async_added_to_hass
    self._current_item = await self.meural.get_item(int(self._gallery_status["current_item"]))
  File "/home/homeassistant/.homeassistant/custom_components/meural/pymeural.py", line 93, in get_item
    return await self.request("get", f"items/{item_id}")
  File "/home/homeassistant/.homeassistant/custom_components/meural/pymeural.py", line 46, in request
    resp = await self.session.request(
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/client.py", line 588, in _request
    resp.raise_for_status()
  File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 941, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url='https://api.meural.com/v0/items/162212'

I know that the username and password I entered when setting up the integration are correct.

**Comment by GuySie** [comment]
Hey @gergles sorry to hear that. It seems to fail on initially getting the data on the current item being displayed by your device, which for some reason is forbidden to you according to the API. Could you try what happens if you delete the integration, change your Meural device to a different gallery and a different photo being displayed using the Meural app, and reinstall the integration? I wonder if it has something to do with that specific item, or if it's a broader problem.

**Comment by gergles** [comment]
I have done that and the issue persists, but the numeric portion of the end
of the URL changes.

If there’s additional logging or anything that would help, please let me
know.

Initially when i added the integration, the canvas was asleep, but this
time I made sure it wasn’t before adding the integration.

**Comment by gergles** [comment]
For what it’s worth, the app doesn’t seem to know what I’m playing either.
It always says “Playlist not available” even if I change it to a different
playlist through the app. Not sure how else to troubleshoot that. :/

**Comment by GuySie** [comment]
There's not a lot of logging built into the integration - mainly because I haven't done much troubleshooting so far - so additional logging would not help much. But it's interesting that the app also doesn't know what is playing. It uses the same API, so that would suggest the API response is not just forbidden to this integration.

Are these playlists you're switching to from Meural themselves, or are they playlists that you created through the Meural website, or via the app? Or maybe are you using local folders on the SD card? 

(Because now that I think about it, I have never tested this integration with the SD card because I don't use my device that way, and I can see some problems in getting data from the Meural API when it doesn't even know what's on the SD.)

**Comment by GuySie** [comment]
Hi @gergles I've gotten around to doing some SD card testing and can get the same behavior to occur when I launch Home Assistant while my Meural is set to display a playlist from a local SD card - because the item currently displayed is unknown to the API. The error keeps the integration from launching.

Difference between my logs and yours is that my numbers are very low, eg:
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://api.meural.com/v0/items/1')

But you may have been using the meural for longer and have more images on there. 

Can you confirm if you're using the local SD card to display playlists, just to make sure?

Either way I have to make sure the integration doesnt fail if it can't load the item, and that should at least get the integration launched in HA.

**Comment by GuySie** [comment]
@gergles I've created a work-around that fixed my SD-card scenario, it's available in the current dev branch:
https://github.com/GuySie/ha-meural/blob/dev/custom_components/meural/media_player.py

I'm not sure if this will also resolve your issues, as I'm not sure yet what is causing the API error messages you're getting, but at the very least the error should no longer cause the integration to fail setup.

Could you copy this media_player.py file into your custom_components/meural folder and restart HA? Let me know if it fixes your issue!

**Comment by gergles** [comment]
Using your workaround I am able to pair and control my canvas as expected.
It does show what is playing on it and appears to work as designed. I can
change playlists and navigate through them. Next to try is putting a custom
image on it (which is what I really wanted to do all along) but I'm
thrilled to have this functionality working already!

I do not have an SD card in my canvas at all, so I can't help with that
troubleshooting unfortunately.

**Comment by GuySie** [comment]
@gergles Great! I still don't understand why you're getting those forbidden responses from the API, but happy to see that the fix for the SD-card scenario also works for you. 

I've added warning-level logging whenever it gets an error reponse from the API while trying to access an item, you may want to keep an eye out on that to see if it happens to you a lot. Looks like this:
"Meural device: Can't get local currently displayed item from remote API, resetting item information"

I'll test this version a little bit more and then update the master release so you can just install from HACS again.

**Comment by GuySie** [comment]
Released in v.0.1.3.
